-- Cloudflare D1 数据库架构

CREATE TABLE IF NOT EXISTS users (
  uid INTEGER PRIMARY KEY AUTOINCREMENT,
  user TEXT UNIQUE NOT NULL,
  pwd TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user TEXT NOT NULL,
  uid INTEGER NOT NULL,
  msg TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
  postId INTEGER PRIMARY KEY AUTOINCREMENT,
  uid INTEGER NOT NULL,
  user TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  like_count INTEGER DEFAULT 0,
  time TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid INTEGER NOT NULL,
  postId INTEGER NOT NULL,
  UNIQUE(uid, postId)
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  postId INTEGER NOT NULL,
  uid INTEGER NOT NULL,
  user TEXT NOT NULL,
  content TEXT NOT NULL,
  time TEXT NOT NULL
);
