name = "ratstudio"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "ratstudio-db"
database_id = "3ff87e32-8f63-4d1b-a50f-3ce65d73932f"
# 本地开发配置
[dev]
port = 8787
